// Generated by Tekes/scripts/generate-session-event-registry.py. Do not edit.
// Source: Tekes/docs/session-event-registry-v1.canonical.json

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum SessionEventProjectionKind {
    Folded,
    StateOnly,
    Surface,
    Transient,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum SessionEventUiAuthority {
    Event,
    None,
    TypedEndpoint,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum SessionEventProducer {
    Codex,
    Dsh,
    Kernel,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) struct SessionEventRegistryEntry {
    pub(crate) event_type: &'static str,
    pub(crate) projection: SessionEventProjectionKind,
    #[allow(dead_code)]
    pub(crate) ui_authority: SessionEventUiAuthority,
    pub(crate) producers: &'static [SessionEventProducer],
}

pub(crate) const SESSION_EVENT_REGISTRY: &[SessionEventRegistryEntry] = &[
    SessionEventRegistryEntry {
        event_type: "agent-preset/selected",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::TypedEndpoint,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "agent/inbox/spliced",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::None,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "approval/asked",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::TypedEndpoint,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "approval/decided",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::TypedEndpoint,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "approval/policy",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::TypedEndpoint,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "assistant/attempt",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::None,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "assistant/chunk",
        projection: SessionEventProjectionKind::Transient,
        ui_authority: SessionEventUiAuthority::Event,
        producers: &[
            SessionEventProducer::Codex,
            SessionEventProducer::Dsh,
            SessionEventProducer::Kernel,
        ],
    },
    SessionEventRegistryEntry {
        event_type: "assistant/message",
        projection: SessionEventProjectionKind::Surface,
        ui_authority: SessionEventUiAuthority::Event,
        producers: &[
            SessionEventProducer::Codex,
            SessionEventProducer::Dsh,
            SessionEventProducer::Kernel,
        ],
    },
    SessionEventRegistryEntry {
        event_type: "command/done",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::TypedEndpoint,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "command/run",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::TypedEndpoint,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "compaction/end",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::None,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "compaction/prune",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::None,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "compaction/start",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::None,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "compaction/summary",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::None,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "deliverables/presented",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::None,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "developer/message",
        projection: SessionEventProjectionKind::Surface,
        ui_authority: SessionEventUiAuthority::Event,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "feedback/message-delete",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::None,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "feedback/message-put",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::None,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "feedback/record",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::TypedEndpoint,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "goal/change",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::TypedEndpoint,
        producers: &[SessionEventProducer::Codex, SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "hook/invoked",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::None,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "hook/result",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::None,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "image/offload",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::None,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "llm/retry",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::None,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "llm/retry-started",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::None,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "model/selection",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::TypedEndpoint,
        producers: &[SessionEventProducer::Codex, SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "permission/preset",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::TypedEndpoint,
        producers: &[SessionEventProducer::Codex, SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "plan/mode",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::TypedEndpoint,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "request/context",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::None,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "request/header",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::None,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "response/error",
        projection: SessionEventProjectionKind::Surface,
        ui_authority: SessionEventUiAuthority::Event,
        producers: &[SessionEventProducer::Codex, SessionEventProducer::Kernel],
    },
    SessionEventRegistryEntry {
        event_type: "sandbox/mode",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::TypedEndpoint,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "schedule/change",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::TypedEndpoint,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "session-log-deepseek/delivery-accepted",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::None,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "session/end-seed",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::None,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "session/notice",
        projection: SessionEventProjectionKind::Surface,
        ui_authority: SessionEventUiAuthority::Event,
        producers: &[SessionEventProducer::Kernel],
    },
    SessionEventRegistryEntry {
        event_type: "session/title",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::TypedEndpoint,
        producers: &[
            SessionEventProducer::Codex,
            SessionEventProducer::Dsh,
            SessionEventProducer::Kernel,
        ],
    },
    SessionEventRegistryEntry {
        event_type: "session/title-llm-request",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::None,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "step/end",
        projection: SessionEventProjectionKind::Folded,
        ui_authority: SessionEventUiAuthority::Event,
        producers: &[SessionEventProducer::Dsh, SessionEventProducer::Kernel],
    },
    SessionEventRegistryEntry {
        event_type: "step/start",
        projection: SessionEventProjectionKind::Folded,
        ui_authority: SessionEventUiAuthority::Event,
        producers: &[SessionEventProducer::Dsh, SessionEventProducer::Kernel],
    },
    SessionEventRegistryEntry {
        event_type: "subagent/catalog",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::None,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "subagent/descriptor",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::TypedEndpoint,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "subagent/model-selection-policy",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::TypedEndpoint,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "system/message",
        projection: SessionEventProjectionKind::Surface,
        ui_authority: SessionEventUiAuthority::Event,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "team/member",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::TypedEndpoint,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "team/message/delivered",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::TypedEndpoint,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "team/message/queued",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::TypedEndpoint,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "team/task",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::TypedEndpoint,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "todo/write",
        projection: SessionEventProjectionKind::Folded,
        ui_authority: SessionEventUiAuthority::Event,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "tool-workflow/agent-end",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::None,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "tool-workflow/agent-start",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::None,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "tool-workflow/run-end",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::None,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "tool-workflow/run-start",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::None,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "tool/call",
        projection: SessionEventProjectionKind::Folded,
        ui_authority: SessionEventUiAuthority::Event,
        producers: &[
            SessionEventProducer::Codex,
            SessionEventProducer::Dsh,
            SessionEventProducer::Kernel,
        ],
    },
    SessionEventRegistryEntry {
        event_type: "tool/code-dispatch",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::None,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "tool/code-dispatch-start",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::None,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "tool/ptc-dispatch",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::None,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "tool/ptc-dispatch-start",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::None,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "tool/result",
        projection: SessionEventProjectionKind::Surface,
        ui_authority: SessionEventUiAuthority::Event,
        producers: &[
            SessionEventProducer::Codex,
            SessionEventProducer::Dsh,
            SessionEventProducer::Kernel,
        ],
    },
    SessionEventRegistryEntry {
        event_type: "turn/end",
        projection: SessionEventProjectionKind::Folded,
        ui_authority: SessionEventUiAuthority::Event,
        producers: &[
            SessionEventProducer::Codex,
            SessionEventProducer::Dsh,
            SessionEventProducer::Kernel,
        ],
    },
    SessionEventRegistryEntry {
        event_type: "turn/start",
        projection: SessionEventProjectionKind::Folded,
        ui_authority: SessionEventUiAuthority::Event,
        producers: &[
            SessionEventProducer::Codex,
            SessionEventProducer::Dsh,
            SessionEventProducer::Kernel,
        ],
    },
    SessionEventRegistryEntry {
        event_type: "user/message",
        projection: SessionEventProjectionKind::Surface,
        ui_authority: SessionEventUiAuthority::Event,
        producers: &[
            SessionEventProducer::Codex,
            SessionEventProducer::Dsh,
            SessionEventProducer::Kernel,
        ],
    },
    SessionEventRegistryEntry {
        event_type: "web/deepseek-search-llm-request",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::None,
        producers: &[SessionEventProducer::Dsh],
    },
    SessionEventRegistryEntry {
        event_type: "workspace/changes",
        projection: SessionEventProjectionKind::StateOnly,
        ui_authority: SessionEventUiAuthority::None,
        producers: &[SessionEventProducer::Dsh],
    },
];

pub(crate) fn session_event_registry_entry(
    event_type: &str,
) -> Option<&'static SessionEventRegistryEntry> {
    SESSION_EVENT_REGISTRY
        .iter()
        .find(|entry| entry.event_type == event_type)
}

pub(crate) fn is_surface_event_type(event_type: &str) -> bool {
    session_event_registry_entry(event_type)
        .is_some_and(|entry| entry.projection == SessionEventProjectionKind::Surface)
}

pub(crate) fn kernel_may_emit_event_type(event_type: &str) -> bool {
    session_event_registry_entry(event_type)
        .is_some_and(|entry| entry.producers.contains(&SessionEventProducer::Kernel))
}
