[package]
name = "provider"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
base64.workspace = true
futures-util.workspace = true
libc.workspace = true
profile = { path = "../profile" }
reqwest.workspace = true
schema = { path = "../schema" }
serde.workspace = true
serde_json.workspace = true
serde_json_canonicalizer.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
zeroize.workspace = true

[dev-dependencies]
engine = { path = "../engine" }
tempfile.workspace = true
test-support = { path = "../test-support" }

[lints.rust]
unsafe_code = "allow"
unsafe_op_in_unsafe_fn = "deny"

[lints.clippy]
all = "warn"
